[build]
  # サーバーレス関数のコードが置かれているディレクトリを指定します。
  # この例では、リポジトリのルートにある 'netlify/functions' フォルダです。
  functions = "netlify/functions"
  
  # 静的サイトの公開ディレクトリを指定します。
  # '.' はリポジトリのルートディレクトリを意味します。
  # あなたの index.html がルートにある場合、これでOKです。
  publish = "."                  

# リダイレクトルールを定義します。
# これにより、フロントエンド（ブラウザ）から '/weather-api' にアクセスすると、
# 内部的にサーバーレス関数 '/.netlify/functions/get-weather' が呼び出されます。
# APIキーがURLに露出するのを防ぐために推奨されます。
[[redirects]]
  from = "/weather-api" 
  to = "/.netlify/functions/get-weather" 
  status = 200 # 成功レスポンスとして返す